### ISSUE TITLE
stream_audio.js: remaining port when killed

### ISSUE THREAD

**Issue by bhigy** [robotology/yarp.js#8]
When the server is killed (like when you use yarpmanager) the port remains open. I found a way to correct this using following code:
```
//catches termination event
process.on('SIGTERM', function () {
    console.log('Caught SIGTERM...');
    process.exit(2);
});
```

However, everything seems to be fine if when the server is shut down using CTRL-C. Any idea why (maybe @vtikha)?

**Comment by cciliber** [comment]
Thanks! Yes, your solution is the correct one. I added it to the code. 

Indeed, up to now the code in yarp.js was only listening for SIGINT events (that's why it was working with CTRL-C) but not SIGTERM. Now it is : )  Thanks!

BTW: is there a reason for requiring the process to exit with exit code `2`? At the moment I just exit with the default `0` (which stands for success).

**Comment by bhigy** [comment]
No idea. I copied the code from somewhere else and it was like this :) I guess it depends if you consider SIGTERM as a normal way terminating (as in our case) or not.
