### ISSUE TITLE
stream_audio.js: delay introduced when restarting the server

### ISSUE THREAD

**Issue by bhigy** [robotology/yarp.js#9]
While coding and debugging, I start and stop the server quit often, sometimes leaving the webpage open with the mic on. To be clear, let's say I do the following:
t1 - start server and connect through a browser, turn the streaming on
t2 - stop the server but keep the page open with the mic turned on
t3 - restart the server
Then there is a delay in the streaming. The data is buffered somewhere and the data streamed is not from t3 but t2. Any idea why?

**Comment by cciliber** [comment]
That's a funny behavior :)
I think it is because you are using the implementation based upon socket.io stream objects. Stream objects keep piling up stuff until someone does not read from them. Therefore, since the server was not running, the object was piling up audio stream. Only when you would reconnect the server you would start "deflating" the stream object. So the solution here would be to reload the page when you restart the server.

However, I recently wrote another implementation that uses standard socket.io messages instead of stream objects. This should bypass the problem you observed. I have not tested it yet. I put it in a bundle of examples. You can run it by `node examples/examples.js` and be a tester :) I would be glad to hear your feedback on it.

**Comment by bhigy** [comment]
That make sense. Thanks!

I wanted to try the non-stream version but as the port is only opened when you load the page, it's hard to replicate the problem as is.

**Comment by cciliber** [comment]
Ok, anyways, if you try the non-stream version let me know if there are any delays in the audio. Because with my current hardware I cannot debug it.
